default:
  image: 
    name: banst/awscli
    entrypoint: [""]

stages:  
   - deploy

deploy:
  stage: deploy
  script:
    - aws configure set region us-east-1
    - aws s3 cp  --recursive ixviewer-src s3://hdata-ixviewer-test/
    - aws cloudfront create-invalidation --distribution-id E2L2EJLJQ07W1J --paths '/*'